services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
  db:
    build: 
      context: "."
      dockerfile: "db.Dockerfile"