services:
  app:
    build: .
    tty: true
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
  db:
    build: 
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - todo-db-data:/var/lib/postgresql/data
volumes:
  todo-db-data:
    external: true